"""add access_token_jti_hash to user_sessions

Revision ID: 014585e6af90
Revises: 855ee4feabb0
Create Date: 2025-12-17 05:06:27.105278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014585e6af90'
down_revision: Union[str, Sequence[str], None] = '855ee4feabb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('access_token_jti_hash', sa.String(length=64), nullable=False))
    op.add_column('user_sessions', sa.Column('refresh_token_jti_hash', sa.String(length=64), nullable=False))
    op.add_column('user_sessions', sa.Column('previous_refresh_token_jti_hash', sa.String(length=64), nullable=True))
    op.drop_index(op.f('ix_user_sessions_jti_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_previous_jti_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_access_token_jti_hash'), 'user_sessions', ['access_token_jti_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_previous_refresh_token_jti_hash'), 'user_sessions', ['previous_refresh_token_jti_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_jti_hash'), 'user_sessions', ['refresh_token_jti_hash'], unique=True)
    op.drop_column('user_sessions', 'jti_hash')
    op.drop_column('user_sessions', 'previous_jti_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('previous_jti_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('user_sessions', sa.Column('jti_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_sessions_refresh_token_jti_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_previous_refresh_token_jti_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_access_token_jti_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_previous_jti_hash'), 'user_sessions', ['previous_jti_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_jti_hash'), 'user_sessions', ['jti_hash'], unique=True)
    op.drop_column('user_sessions', 'previous_refresh_token_jti_hash')
    op.drop_column('user_sessions', 'refresh_token_jti_hash')
    op.drop_column('user_sessions', 'access_token_jti_hash')
    # ### end Alembic commands ###
