"""add_user_sessions_with_status_and_update_token_blacklist

Revision ID: 855ee4feabb0
Revises: 302ec4aa7dea
Create Date: 2025-12-17 03:44:56.366208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '855ee4feabb0'
down_revision: Union[str, Sequence[str], None] = '302ec4aa7dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_jti_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_jti_hash'), 'user_sessions', ['jti_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_previous_jti_hash'), 'user_sessions', ['previous_jti_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_status'), 'user_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.add_column('token_blacklist', sa.Column('jti_hash', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.create_index(op.f('ix_token_blacklist_jti_hash'), 'token_blacklist', ['jti_hash'], unique=False)
    op.drop_column('token_blacklist', 'jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_blacklist', sa.Column('jti', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_token_blacklist_jti_hash'), table_name='token_blacklist')
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=False)
    op.drop_column('token_blacklist', 'jti_hash')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_status'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_previous_jti_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_jti_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
